<?php

namespace AE\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdesioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdesioneRepository extends EntityRepository
{
}
