ae_blog:
    resource: "@AEBlogBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_blog:
    resource: "@EphpBlogBundle/Controller/"
    type:     annotation
    prefix:   /
    
ephp_dd1:
    resource: "@PunkAveFileUploaderBundle/Controller/"
    type:     annotation
    prefix:   /
    
ephp_dd2:
    resource: "@EphpDragDropBundle/Controller/"
    type:     annotation
    prefix:   /
    
ae_storia:
    resource: "@AEStoriaBundle/Controller/"
    type:     annotation
    prefix:   /

ae_web:
    resource: "@AEWebBundle/Controller/"
    type:     annotation
    prefix:   /

#Routing del Js bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#FORM TRADUZIONE VALIDAZIONE JS
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

_fos:
    resource: routing_fos_user.yml

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
 
facebook_login:
    pattern: /login/check-facebook
 
#google_login:
#    pattern: /login/check-google 
    
twitter_login:
    pattern: /login/check-twitter
