<?php

namespace AE\StoriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LuogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdizioneRepository extends EntityRepository
{
}
