<?php

namespace AE\StoriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManifestazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManifestazioneRepository extends EntityRepository
{
}
